# Generated by Django 4.2.1 on 2023-05-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_address', models.CharField(max_length=1000, verbose_name='Source')),
                ('destination_address', models.CharField(max_length=1000, verbose_name='Destination')),
                ('distance', models.CharField(max_length=1000, verbose_name='Distance')),
            ],
        ),
    ]
